/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('primevue/avatar')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    CardView: typeof import('./src/components/CardView.vue')['default']
    Carousel: typeof import('primevue/carousel')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    CreateRepDialog: typeof import('./src/components/RepFormDialog.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ItemEditCreateDialog: typeof import('./src/components/ItemEditCreateDialog.vue')['default']
    ItemFormDialog: typeof import('./src/components/ItemFormDialog.vue')['default']
    ItemViewDialog: typeof import('./src/components/ItemViewDialog.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    Popover: typeof import('primevue/popover')['default']
    PreviewItem: typeof import('./src/components/PreviewItem.vue')['default']
    RepFormDialog: typeof import('./src/components/RepFormDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPanel: typeof import('primevue/scrollpanel')['default']
    Select: typeof import('primevue/select')['default']
    SidePanel: typeof import('./src/components/SidePanel.vue')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
